version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: car_rental_db
    environment:
      MYSQL_ROOT_PASSWORD: root      # Change this!
      MYSQL_DATABASE: Car_Rental_System             # Your database name
      MYSQL_USER: user                       # Optional: create an app user
      MYSQL_PASSWORD: root           # Password for that user
    ports:
      - "3307:3306"                          # Host:Container
    volumes:
      - mysql_data:/var/lib/mysql            # Persist data (optional)
      - ./db/init:/docker-entrypoint-initdb.d # Auto-run SQL scripts
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:    # Named volume â€“ keeps data when container restarts